---
- include: install.yml

- name: Insert rssh into /etc/shells
  lineinfile:
    dest: /etc/shells
    line: '/usr/bin/rssh'

- name: Applying rssh configuration
  template:
    src: rssh.conf.j2
    dest: /etc/rssh.conf
    owner: root
    group: root
    mode: 0644

- name: Add rssh users
  user:
    name={{ item.key }}
    shell=/usr/bin/rssh
    home={{ item.value.path }}
  with_dict: "{{ rssh_users }}"
  when: rssh_create_users

...
